function criptografaTexto() {
    var texto = document.getElementById("criptografa").value;
        if (texto == ""){
            alert("Escreva um texto para ser convertido!!!")
            return false;
        }
    var resultado =  texto 
        .replace(/a/g, "#")
        .replace(/á/g, "®")
        .replace(/b/g, "▼")
        .replace(/c/g, "%")
        .replace(/d/g, "Ä")
        .replace(/e/g, "⥂")
        .replace(/f/g, "⥕")
        .replace(/g/g, "ໂ")
        .replace(/h/g, "↶")
        .replace(/i/g, "ℿ")
        .replace(/j/g, "⋘")
        .replace(/k/g, "⥀")
        .replace(/l/g, "`")
        .replace(/m/g, "{")
        .replace(/n/g, ">")
        .replace(/o/g, "⥧")
        .replace(/p/g, "ë")
        .replace(/q/g, "Ë")
        .replace(/r/g, "⤦")
        .replace(/s/g, "⥌")
        .replace(/t/g, "ª")
        .replace(/u/g, "⥳")
        .replace(/v/g, "⍦")
        .replace(/w/g, "└")
        .replace(/x/g, "⥣")
        .replace(/y/g, "Ï")
        .replace(/z/g, "ï")
        .replace(/A/g, "⨆")
        .replace(/B/g, "⨅")
        .replace(/C/g, "№")
        .replace(/D/g, "↑")
        .replace(/E/g, "Ö")
        .replace(/F/g, "ö")
        .replace(/G/g, "⋳")
        .replace(/H/g, "ò")
        .replace(/I/g, "↣")
        .replace(/J/g, "Ò")
        .replace(/K/g, "Ü")
        .replace(/L/g, "ü")
        .replace(/M/g, "↻")
        .replace(/N/g, "ù")
        .replace(/M/g, "Ù")
        .replace(/O/g, "⨇")
        .replace(/P/g, "¨")
        .replace(/Q/g, "┼")
        .replace(/R/g, "¶")
        .replace(/S/g, "§")
        .replace(/T/g, "ý")
        .replace(/U/g, "ÿ")
        .replace(/V/g, "æ")
        .replace(/W/g, "£")
        .replace(/X/g, "ƒ")
        .replace(/Y/g, "Ø")
        .replace(/Z/g, "⥽")
        .replace(/0/g, "¥")
        .replace(/1/g, "µ")
        .replace(/2/g, "ß")
        .replace(/3/g, "©")
        .replace(/4/g, "┴")
        .replace(/5/g, "╔")
        .replace(/6/g, "╦")
        .replace(/7/g, "¤")
        .replace(/8/g, "þ")
        .replace(/9/g, "Ð")
        .replace(/-/g, "┤")
        .replace(/,/g, "¿")
        .replace(/ç/g, "⅀")
        .replace(/é/g, "™")
        .replace(/ú/g, "⍔")
        .replace(/É/g, "⍀")
        .replace(/Ú/g, "ʢ")
        .replace(/â/g, "ʮ")
        .replace(/Â/g, "ʭ")
        .replace(/ó/g, "θ")
        .replace(/Ó/g, "Ϡ")
        .replace(/Ê/g, "ʪ")
        .replace(/ê/g, "ʎ");
    document.getElementById("descriptografa").value = resultado;
    document.getElementById("descriptografa").focus();
}

function descriptografaTexto() {
    var texto = document.getElementById("descriptografa").value;
    if (texto == ""){
        alert("Escreva um texto para ser convertido!!!")
        return false;
    }
    var resultado = texto 
        .replace(/#/g, "a")
        .replace(/®/g, "á")
        .replace(/▼/g, "b")
        .replace(/%/g, "c")
        .replace(/Ä/g, "d")
        .replace(/⥂/g, "e")
        .replace(/⥕/g, "f")
        .replace(/ໂ/g, "g")
        .replace(/↶/g, "h")
        .replace(/ℿ/g, "i")
        .replace(/⋘/g, "j")
        .replace(/⥀/g, "k")
        .replace(/`/g, "l")
        .replace(/{/g, "m")
        .replace(/>/g, "n")
        .replace(/⥧/g, "o")
        .replace(/ë/g, "p")
        .replace(/Ë/g, "q")
        .replace(/⤦/g, "r")
        .replace(/⥌/g, "s")
        .replace(/ª/g, "t")
        .replace(/⥳/g, "u")
        .replace(/⍦/g, "v")
        .replace(/└/g, "w")
        .replace(/⥣/g, "x")
        .replace(/Ï/g, "y")
        .replace(/ï/g, "z")
        .replace(/⨆/g, "A")
        .replace(/⨅/g, "B")
        .replace(/№/g, "C")
        .replace(/↑/g, "D")
        .replace(/Ö/g, "E")
        .replace(/ö/g, "F")
        .replace(/⋳/g, "G")
        .replace(/ò/g, "H")
        .replace(/↣/g, "I")
        .replace(/Ò/g, "J")
        .replace(/Ü/g, "K")
        .replace(/ü/g, "L")
        .replace(/↻/g, "M")
        .replace(/ù/g, "N")
        .replace(/Ù/g, "M")
        .replace(/⨇/g, "O")
        .replace(/¨/g, "P")
        .replace(/┼/g, "Q")
        .replace(/¶/g, "R")
        .replace(/§/g, "S")
        .replace(/ý/g, "T")
        .replace(/ÿ/g, "U")
        .replace(/æ/g, "V")
        .replace(/£/g, "W")
        .replace(/ƒ/g, "X")
        .replace(/Ø/g, "Y")
        .replace(/⥽/g, "Z")
        .replace(/¥/g, "0")
        .replace(/µ/g, "1")
        .replace(/ß/g, "2")
        .replace(/©/g, "3")
        .replace(/┴/g, "4")
        .replace(/╔/g, "5")
        .replace(/╦/g, "6")
        .replace(/¤/g, "7")
        .replace(/þ/g, "8")
        .replace(/Ð/g, "9")
        .replace(/┤/g, "-")
        .replace(/¿/g, ",")
        .replace(/⅀/g, "ç")
        .replace(/™/g, "é")
        .replace(/⍔/g, "ú")
        .replace(/⍀/g, "É")
        .replace(/ʢ/g, "Ú")
        .replace(/ʮ/g, "â")
        .replace(/ʭ/g, "Â")
        .replace(/θ/g, "ó")
        .replace(/Ϡ/g, "Ó")
        .replace(/ʪ/g, "Ê")
        .replace(/ʎ/g, "ê");
    document.getElementById("descriptografa2").value = resultado;
}

function limpaDados() {
    document.getElementById('criptografa').value = '';
    document.getElementById('descriptografa').value = '';
    document.getElementById('descriptografa2').value = '';
    document.getElementById("criptografa").focus();
}

function entendeu() {
    document.getElementById("popup").style.display = "none";
    document.getElementById("corpo").style.display = "block";
    document.getElementById("criptografa").focus();
}